### ISSUE TITLE
服务端如何 ping 某个客户端的连接？

### ISSUE THREAD

**Issue by Allard-Ivan** [fengma312/socket.core#1]
我懂你的意思了。你的意思是如何判断是否是连接状态或断线状态。
我这边会有一个OnClose事件，如果主动断开会触发这个事件，如果是网络断线或停电之类的话，我这边没有处理，需要自己加心跳机制处理。我不打算加心跳/断线重连这类的机制，因为加心跳这东西会限制框架使用范围。

**Comment by Allard-Ivan** [comment]
看来你已经修复了断开事件的 bug，那这个问题算是解决了。

**Comment by Allard-Ivan** [comment]
如题，再问一遍，请道友帮忙解答一下。

**Comment by Allard-Ivan** [comment]
可不可以暴露 ConeectClient 的 keep_alive 属性。

**Comment by fengma312** [comment]
@Allard-Ivan   你需要keep_alive 属性的最终目的是什么？我想不到。这个是超时作用来的，服务端已经做了处理。 应该是不需要调用方干预的呀。
