### ISSUE TITLE
TcpPushClient 连接ZLAN5103内存缓慢增长

### ISSUE THREAD

**Issue by huohhf** [fengma312/socket.core#11]
您好，server端为ZLAN5103转485连接控制设备。最简单场景：client发数据（10byte）, server接收后返回，client收到后重复发（每个往返100ms左右）。发现有内存缓慢增长(24小时10M左右)。而相同的方式连接其他各种server端（java的，c#的）还未发现此现象，无法定位问题，麻烦帮忙判断一下可能是那里的问题？
另，client运行在win2008r2下，netcore2.2独立部署模式， 在win10下似乎没有问题，正在确认中。

附client代码：
            socket.core.Client.TcpPushClient client = new socket.core.Client.TcpPushClient(100);
            client.Connect("192.168.1.202", 4196);
            byte[] data = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 0x0D };

            client.OnReceive += d =>
            {
                Console.WriteLine(BitConverter.ToString(d));
                client.Send(data, 0, data.Length);
            };

            System.Threading.Thread.Sleep(500);
            client.Send(data, 0, data.Length);

**Comment by fengma312** [comment]
这真我还真不知道原因。sorry!
