### ISSUE TITLE
当服务端关闭时，客户端收不到断开事件

### ISSUE THREAD

**Issue by wusaneryi** [fengma312/socket.core#13]
在pack模式下测试，当服务端关闭后，客户端收不到断开事件。
修改了socket.core/client/tcpclients.cs
CloseClientSocket函数：
屏蔽了 //if (!socket.Connected)
            //{
            //    return;
            //}
后，pack模式下可以收到事件通知，push模式下收到2次事件通知

**Comment by fengma312** [comment]
服务端关闭也要分情况，如果是正常的调用框架的关闭事件，肯定会触发断开事件，如果是外部原因断开的话，如直接杀死进程之类的话就不会有了。这样的话，需要你们自己增加心跳机制。。。。
