### ISSUE TITLE
一次发送10条数据，服务器只能收到6条数据

### ISSUE THREAD

**Issue by LiLoveMa** [fengma312/socket.core#14]
一次发送10条数据，服务器只能收到6条数据

**Comment by fengma312** [comment]
不可能的话呀。我测试都没有出去过这情况。

**Comment by zx493734247** [comment]
作者您好,
我在.net core 3.1的Abp项目中用了您的框架.使用的单例模式去注入的.
现在我也遇到同样的问题.在很短的时间内发送大量的请求数据,服务端只收到几个.
如果客户端Sleep 50毫秒,那么能正常收到
我使用了Wireshark进行了抓包,发现服务端给客户端发回了ACK确认了.但是在服务端的Server_OnSend方法中就打印了几个.
![image](https://user-images.githubusercontent.com/18095753/83941835-181a8600-a821-11ea-9ae4-e42a2e4c5da1.png)
![image](https://user-images.githubusercontent.com/18095753/83941854-3aac9f00-a821-11ea-8afc-9d34d7ec0cad.png)
![image](https://user-images.githubusercontent.com/18095753/83941857-48fabb00-a821-11ea-8600-b9d702e38955.png)
@fengma312

**Comment by footman136** [comment]
你好！
我确实没有测试过消息密集发送的情况。你用的是哪个工程？
我回头也测试一下。

刘刚

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: zx493734247 <notifications@github.com>
发送时间: Saturday, June 6, 2020 6:13:14 PM
收件人: fengma312/socket.core <socket.core@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [fengma312/socket.core] 一次发送10条数据，服务器只能收到6条数据 (#14)


作者您好,
我在.net core 3.1的Abp项目中用了您的框架.使用的单例模式去注入的.
现在我也遇到同样的问题.在很短的时间内发送大量的请求数据,服务端只收到几个.
如果客户端Sleep 50毫秒,那么能正常收到
我使用了Wireshark进行了抓包,发现服务端给客户端发回了ACK确认了.但是在服务端的Server_OnSend方法中就打印了几个.
[image]<https://user-images.githubusercontent.com/18095753/83941835-181a8600-a821-11ea-9ae4-e42a2e4c5da1.png>
[image]<https://user-images.githubusercontent.com/18095753/83941854-3aac9f00-a821-11ea-8afc-9d34d7ec0cad.png>
[image]<https://user-images.githubusercontent.com/18095753/83941857-48fabb00-a821-11ea-8600-b9d702e38955.png>
@fengma312<https://github.com/fengma312>

―

**Comment by footman136** [comment]
我看了一下我这边的github，这个fengma312/Socket.Core根本就不是我提交的。。。
不知道为什么会挂在我这里了。。。这个工程是两年前的，而我这个账号注册才8个月。

刘刚

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: zx493734247 <notifications@github.com>
发送时间: Saturday, June 6, 2020 6:13:14 PM
收件人: fengma312/socket.core <socket.core@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [fengma312/socket.core] 一次发送10条数据，服务器只能收到6条数据 (#14)


作者您好,
我在.net core 3.1的Abp项目中用了您的框架.使用的单例模式去注入的.
现在我也遇到同样的问题.在很短的时间内发送大量的请求数据,服务端只收到几个.
如果客户端Sleep 50毫秒,那么能正常收到
我使用了Wireshark进行了抓包,发现服务端给客户端发回了ACK确认了.但是在服务端的Server_OnSend方法中就打印了几个.
[image]<https://user-images.githubusercontent.com/18095753/83941835-181a8600-a821-11ea-9ae4-e42a2e4c5da1.png>
[image]<https://user-images.githubusercontent.com/18095753/83941854-3aac9f00-a821-11ea-8afc-9d34d7ec0cad.png>
[image]<https://user-images.githubusercontent.com/18095753/83941857-48fabb00-a821-11ea-8600-b9d702e38955.png>
@fengma312<https://github.com/fengma312>

―

**Comment by footman136** [comment]
我自作多情了。你确实是发给原作者的，我也确实follow了这个工程，也就是说我在你们的邮件群组里。

哈哈哈

刘刚

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: zx493734247 <notifications@github.com>
发送时间: Saturday, June 6, 2020 6:13:14 PM
收件人: fengma312/socket.core <socket.core@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [fengma312/socket.core] 一次发送10条数据，服务器只能收到6条数据 (#14)


作者您好,
我在.net core 3.1的Abp项目中用了您的框架.使用的单例模式去注入的.
现在我也遇到同样的问题.在很短的时间内发送大量的请求数据,服务端只收到几个.
如果客户端Sleep 50毫秒,那么能正常收到
我使用了Wireshark进行了抓包,发现服务端给客户端发回了ACK确认了.但是在服务端的Server_OnSend方法中就打印了几个.
[image]<https://user-images.githubusercontent.com/18095753/83941835-181a8600-a821-11ea-9ae4-e42a2e4c5da1.png>
[image]<https://user-images.githubusercontent.com/18095753/83941854-3aac9f00-a821-11ea-8afc-9d34d7ec0cad.png>
[image]<https://user-images.githubusercontent.com/18095753/83941857-48fabb00-a821-11ea-8600-b9d702e38955.png>
@fengma312<https://github.com/fengma312>

―

**Comment by fengma312** [comment]
hi,针对这个问题，我周末(2020/6/13)会仔细看看。谢谢。
