### ISSUE TITLE
看您好像只用了.net core 内置的begin的异步方法来实现，确认是IOCP吗？

### ISSUE THREAD

**Issue by meision** [fengma312/socket.core#2]
两个问题：
1. 看您好像只用了.net core 内置的begin的异步方法来实现，确认是IOCP吗？
2. 不推荐弄一个线程去wait时间去发送，如果是异步的话压根用不着用统一的线程去对socket进行send,如果是非要这样实现的话，要加入一个信号量，在这里的话，set信号量
 internal void Send(byte[] data, int offset, int length)
        {
            sendQueue.Enqueue(new SendingQueue() { data = data, offset = offset, length = length });
        }
在下边的话while信号量。
   while (true)
            {
                SendingQueue sending;
                if (sendQueue.TryDequeue(out sending))
                {
                    Send(sending);
                }
                else
                {
                    Thread.Sleep(100);
                }
            }

**Comment by fengma312** [comment]
Report content: https://github.com/fengma312/socket.core/issues/2
第一个问题
       确定是iocp ,C#使用iocp一般两种方式。
       第一种：是调用window api实现。
       第二种：调用Socket类的BeginXXXX/EndXXXX或XXXXAsync。
但使用BeginXXXX/EndXXXX这种异步方式所使用的IAsyncResult 是无法重用，严重消耗资源，所以微软增加了XXXXAsync异步方式，使用的SocketAsyncEventArgs对象是可以重复使用，提高性能。

第二个问题
       请更新代码，这一块已经改了。已经不是你贴出的代码了。现在的异步发送使用了多线程+多个发送队列方式（v1.0.11），同样也没有作用锁的机制，我做过压力测试，使用锁会严重影响性能，至少降低30%的IO，最后才确定使用不加锁的队列，这样性能是最好的。


硬件：cpu i3 4130 ,内存8G  
socket.core :v1.0.11
![qq 20180124092535](https://user-images.githubusercontent.com/5856437/35309668-93d71ba6-00e8-11e8-8c76-f019b435dad8.png)
