### ISSUE TITLE
请问有没有考虑使用System.IO.Pipelines类库来实现？

### ISSUE THREAD

**Issue by ElderJames** [fengma312/socket.core#6]

**Comment by fengma312** [comment]
哥们，跟你说句实在话吧，其实System.IO.Pipelines这个类库我都没有了解，这是第一次听说这个，后面才查资料去了解一点点这个。如果你有空，可以帮我实现，到时我会测试这个性能是否更高，吞吐量是否更大，如果测试通过了。我会合并你的代码。^_^
