### ISSUE TITLE
你好，请教一个问题，使用这个框架，服务端如何获取已连接的客户端的IP信息？

### ISSUE THREAD

**Issue by 960428987** [fengma312/socket.core#8]

**Comment by fengma312** [comment]
哈哈。我仔细查看了这个框架的代码，你提的这个要求好像真的被我给封死了。等我有空了，我会更新这个框架，给你提供一个实时Dictionary<connectId,ip>数据字典。
或者你帮增加这个功能，到时我把你代码合并到这个框架中，(注意：隔离核心类TcpServer.connectClient)

**Comment by 960428987** [comment]
好的！

**Comment by 960428987** [comment]
你好，这个问题根据你的意见我已经修复好了，你看一下修改的对不！
[TcpPushServer.txt](https://github.com/fengma312/socket.core/files/2628314/TcpPushServer.txt)

**Comment by 960428987** [comment]
上面那个文件发错了，
[TcpPushServer.txt](https://github.com/fengma312/socket.core/files/2628356/TcpPushServer.txt)

**Comment by fengma312** [comment]
你在多线程下测试一下看会不会有bug,如果没有bug,你就把三种模式，push，pull,pack三种模式都改了吧。并且提交代码（fork->pul requests），我直接合并代码就行了。

**Comment by fengma312** [comment]
我已经更新了代码，nuget也更新了。版本1.0.14.
上次你更新的代码有bug，所以没有采用你的代码。我自己写了这块代码。
