### ISSUE TITLE
on_close 意外断开问题

### ISSUE THREAD

**Issue by ygxw** [fengma312/socket.core#9]
HI，

我发现一个小问题，作者能否确认或者修复下？
如果我在server使用了overtime，然后client使用心跳配合。当client程序正常运行状况下，我故意让client不发送心跳包，然后心跳机制没问题，server会主动断开该client。
但是，如果我通过“任务管理器”强制关闭client程序，server端将不会发现client端断开了（哪怕超过overtime也不会断开）。

**Comment by fengma312** [comment]
狗日的，你是大哥，隐藏这么深的bug居然还能被发现，不过已经改过来了。已经更新到github了，过几天更新nuget包，快一年没有碰这个项目了。哎。

**Comment by ygxw** [comment]
测试了下你在nuget上的版本，还是有问题，依然没有断开意外中断的客户端。我又简单在github里看了下你的源码，版本号：【268664de6f6282ac5d8110b6ae574477abf46582】，【line：494】。是否在代码后面多了个return
